<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as BaseVerifier;
use Illuminate\Session\TokenMismatchException;


class VerifyCsrfToken extends BaseVerifier
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        //
    ];

    public function handle($request, \Closure $next)
    {
        try{
            return parent::handle($request, $next); // TODO: Change the autogenerated stub
        }catch (TokenMismatchException $e)
        {
            return back()->withInput()->withErrors('Votre jeton de sécurité a expriré ! Veuillez recommencer SVP !');
        }
    }
}
